// Code generated by Kitex v0.5.0. DO NOT EDIT.

package calculator

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "github.com/zzxwill/kitex-demo/kitex_gen/api"
)

func serviceInfo() *kitex.ServiceInfo {
	return calculatorServiceInfo
}

var calculatorServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "calculator"
	handlerType := (*api.Calculator)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetMaximal": kitex.NewMethodInfo(getMaximalHandler, newCalculatorGetMaximalArgs, newCalculatorGetMaximalResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.0",
		Extra:           extra,
	}
	return svcInfo
}

func getMaximalHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.CalculatorGetMaximalArgs)
	realResult := result.(*api.CalculatorGetMaximalResult)
	success, err := handler.(api.Calculator).GetMaximal(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalculatorGetMaximalArgs() interface{} {
	return api.NewCalculatorGetMaximalArgs()
}

func newCalculatorGetMaximalResult() interface{} {
	return api.NewCalculatorGetMaximalResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetMaximal(ctx context.Context, request *api.GetMaximalRequest) (r *api.GetMaximalResponse, err error) {
	var _args api.CalculatorGetMaximalArgs
	_args.Request = request
	var _result api.CalculatorGetMaximalResult
	if err = p.c.Call(ctx, "GetMaximal", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
